import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import {
  getAuth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
  sendPasswordResetEmail,
  onAuthStateChanged,
  signOut,
  deleteUser,
  EmailAuthProvider,
  reauthenticateWithCredential,
  fetchSignInMethodsForEmail,
  updatePassword,
  verifyPasswordResetCode, // Add this import
  confirmPasswordReset, // Add this import
} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import {
  getFirestore,
  setDoc,
  doc,
  getDoc,
  collection,
  getDocs,
  query,
  where,
  updateDoc,
  deleteDoc,
  serverTimestamp,
  addDoc,
  orderBy,
  limit,
  deleteField,
  onSnapshot,
  increment,
  or,
  startAfter,
  and,
  Timestamp,
} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
const firebaseConfig = {
  apiKey: "AIzaSyDhV0RW9BRTIPxyGb6p1xgcnqeHV-yijKg",
  authDomain: "vivarq-argentina.firebaseapp.com",
  projectId: "vivarq-argentina",
  storageBucket: "vivarq-argentina.firebasestorage.app",
  messagingSenderId: "317459457081",
  appId: "1:317459457081:web:b1df2d51ff34b3339299e8",
  measurementId: "G-E37WG2MBYY",
};
const app = initializeApp(firebaseConfig);
const auth = getAuth();
const db = getFirestore();
export {
  getAuth,
  Timestamp,
  EmailAuthProvider,
  updatePassword,
  or,
  and,
  startAfter,
  serverTimestamp,
  fetchSignInMethodsForEmail,
  addDoc,
  auth,
  orderBy,
  increment,
  onSnapshot,
  deleteField,
  limit,
  db,
  createUserWithEmailAndPassword,
  setDoc,
  deleteUser,
  deleteDoc,
  doc,
  reauthenticateWithCredential,
  signInWithEmailAndPassword,
  sendPasswordResetEmail,
  onAuthStateChanged,
  signOut,
  getDoc,
  getFirestore,
  updateDoc,
  collection,
  getDocs,
  query,
  where,
  verifyPasswordResetCode, // Add this export
  confirmPasswordReset, // Add this export
};
